In [ ]:
from google.colab import files
uploaded = files.upload()

Saving safeUnsafe.xlsx to safeUnsafe.xlsx


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy  as np

In [ ]:
data = pd.read_excel('safeUnsafe.xlsx')
# Dataset is now stored in a Pandas Dataframe

In [ ]:
data


Area                 Zone       Time People.Frequency  \
0        Ramapuram       Aanandam Nagar    Morning           Medium   
1        Ramapuram       Aanandam Nagar  Afternoon             High   
2        Ramapuram       Aanandam Nagar    Evening           Medium   
3        Ramapuram       Aanandam Nagar      Night              Low   
4        Ramapuram          Ambal Nagar    Morning           Medium   
..             ...                  ...        ...              ...   
99       Ramapuram  Venkateshwara Nagar      Night              Low   
100  West Mambalam     Vivekanandapuram    Morning             High   
101  West Mambalam     Vivekanandapuram  Afternoon           Medium   
102  West Mambalam     Vivekanandapuram    Evening             High   
103  West Mambalam     Vivekanandapuram      Night              Low   

    Is.Police_Station Is.Bar   Class  
0                 Yes     No    Safe  
1                 Yes     No    Safe  
2                 Yes     No    Safe  
3                 Yes     No    Safe  
4                  No     No    Safe  
..                ...    ...     ...  
99                 No     No  Unsafe  
100                No     No    Safe  
101                No     No    Safe  
102                No     No    Safe  
103                No     No  Unsafe  

[104 rows x 7 columns]

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Area').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Time').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('People.Frequency').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Is.Police_Station').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Time']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Time'}, axis=1)
              .sort_values('Time', ascending=True))
  xs = counted['Time']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Area')):
  _plot_series(series, series_name, i)
  fig.legend(title='Area', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Time')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Time']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Time'}, axis=1)
              .sort_values('Time', ascending=True))
  xs = counted['Time']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Time')):
  _plot_series(series, series_name, i)
  fig.legend(title='Time', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Time')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Time']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Time'}, axis=1)
              .sort_values('Time', ascending=True))
  xs = counted['Time']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('People.Frequency')):
  _plot_series(series, series_name, i)
  fig.legend(title='People.Frequency', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Time')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Time']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Time'}, axis=1)
              .sort_values('Time', ascending=True))
  xs = counted['Time']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Time', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Is.Police_Station')):
  _plot_series(series, series_name, i)
  fig.legend(title='Is.Police_Station', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Time')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Time'].value_counts()
    for x_label, grp in data.groupby('Area')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Area')
_ = plt.ylabel('Time')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['People.Frequency'].value_counts()
    for x_label, grp in data.groupby('Time')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Time')
_ = plt.ylabel('People.Frequency')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Is.Police_Station'].value_counts()
    for x_label, grp in data.groupby('People.Frequency')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('People.Frequency')
_ = plt.ylabel('Is.Police_Station')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Is.Bar'].value_counts()
    for x_label, grp in data.groupby('Is.Police_Station')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Is.Police_Station')
_ = plt.ylabel('Is.Bar')

In [ ]:
from sklearn import preprocessing
# create the Labelencoder object
from sklearn.preprocessing import LabelEncoder

area=['Ramapuram','Adyar','West Mambalam']

people=['Low','Medium','High']
police = ['Yes', 'No']
bar=['Yes', 'No']
enc = LabelEncoder().fit(area)
data['Area'] = enc.transform(data['Area'])
zone=['Aanandam Nagar','Ambal Nagar','Amman Nagar','Baktavatsalm Nagar','Chidambaram Nagar','Easwaran Nagar','Gokulam Colony','Kasi Viswanathar Colony','Moogambigai Nagar','Moovendar Colony','Mullai Nagar','Pannerselvam Nagar','Postal Colony','RamaKrishnapuram','Royala Nagar','Sakthi Nagar','Shastri Nagar','South Kesavaperumalpuram','Subramaniam Nagar','Suresh Nagar','Tamil Nagar','Teachers Colony','Thiru Nagar','Venkateshwar Nagar','Venkateshwara Nagar','Vivekanandapuram']
enc1 = LabelEncoder().fit(zone)
data['Zone'] = enc1.transform(data['Zone'])
time=['Morning','Afternoon','Evening','Night']
enc2 = LabelEncoder().fit(time)
data['Time'] = enc2.transform(data['Time'])
enc3 = LabelEncoder().fit(people)
data['People.Frequency'] = enc3.transform(data['People.Frequency'])
enc4 = LabelEncoder().fit(police)
data['Is.Police_Station'] = enc4.transform(data['Is.Police_Station'])
enc5 = LabelEncoder().fit(bar)
data['Is.Bar'] = enc5.transform(data['Is.Bar'])
#print(data['Is.Police_Station'])
#le = preprocessing.LabelEncoder()
#convert the categorical columns into numeric
# data['Area'] = le.fit_transform(data['Area'])
# data['Zone'] = le.fit_transform(data['Zone'])
# data['Time'] = le.fit_transform(data['Time'])
# data['People.Frequency'] = le.fit_transform(data['People.Frequency'])
# data['Is.Police_Station'] = le.fit_transform(data['Is.Police_Station'])
# data['Is.Bar'] = le.fit_transform(data['Is.Bar'])
# data['Class'] = le.fit_transform(data['Class'])
# print(le.classes_)
#display the initial records
data.head()

Area  Zone  Time  People.Frequency  Is.Police_Station  Is.Bar Class
0     1     0     2                 2                  1       0  Safe
1     1     0     0                 0                  1       0  Safe
2     1     0     1                 2                  1       0  Safe
3     1     0     3                 1                  1       0  Safe
4     1     1     2                 2                  0       0  Safe

In [ ]:
from sklearn.model_selection import train_test_split
y=data.Class
#y
x=data.drop('Class',axis=1)
x

Area  Zone  Time  People.Frequency  Is.Police_Station  Is.Bar
0       1     0     2                 2                  1       0
1       1     0     0                 0                  1       0
2       1     0     1                 2                  1       0
3       1     0     3                 1                  1       0
4       1     1     2                 2                  0       0
..    ...   ...   ...               ...                ...     ...
99      1    24     3                 1                  0       0
100     2    25     2                 0                  0       0
101     2    25     0                 2                  0       0
102     2    25     1                 0                  0       0
103     2    25     3                 1                  0       0

[104 rows x 6 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train.head()

Area  Zone  Time  People.Frequency  Is.Police_Station  Is.Bar
68     0    17     2                 1                  0       0
89     1    22     0                 0                  1       0
95     0    23     3                 1                  0       0
72     0    18     2                 2                  1       1
90     1    22     1                 2                  1       0

In [ ]:
##Linear SVM- Using this!!

from sklearn.svm import SVC

#Create a svm Classifier
svclassifier= SVC( kernel='linear')
#Train the model using the training sets
svclassifier.fit(x_train,y_train)

# Making Predictions

y_pred=svclassifier.predict(x_test)

In [ ]:
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8095238095238095


In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8, gamma='auto')
# gamma is optional. But it gives a FutureWarning. To avoid it , specify
# gamma as 'auto' or 'scale'

svclassifier.fit(x_train, y_train)

# Making Predictions
# Now once we have trained the algorithm,
# the next step is to make predictions on the test data.
y_pred = svclassifier.predict(x_test)


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Note : Note the misclassification in 'virginica' species

[[12  3]
 [ 4  2]]
              precision    recall  f1-score   support

        Safe       0.75      0.80      0.77        15
      Unsafe       0.40      0.33      0.36         6

    accuracy                           0.67        21
   macro avg       0.57      0.57      0.57        21
weighted avg       0.65      0.67      0.66        21



In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf', gamma='auto')
svclassifier.fit(x_train, y_train)

# Prediction and Evaluation
y_pred = svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Note : Note the best performance thats 100% precise

[[14  1]
 [ 5  1]]
              precision    recall  f1-score   support

        Safe       0.74      0.93      0.82        15
      Unsafe       0.50      0.17      0.25         6

    accuracy                           0.71        21
   macro avg       0.62      0.55      0.54        21
weighted avg       0.67      0.71      0.66        21



In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid', gamma='auto')
svclassifier.fit(x_train, y_train)

# Prediction and Evaluation
y_pred = svclassifier.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Note : Note the very poor perfomance from Sigmoid kernel

[[14  1]
 [ 6  0]]
              precision    recall  f1-score   support

        Safe       0.70      0.93      0.80        15
      Unsafe       0.00      0.00      0.00         6

    accuracy                           0.67        21
   macro avg       0.35      0.47      0.40        21
weighted avg       0.50      0.67      0.57        21



In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(x_train, y_train)

# make predictions on the test data

y_pred = classifier.predict(x_test)


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14  1]
 [ 3  3]]
              precision    recall  f1-score   support

        Safe       0.82      0.93      0.87        15
      Unsafe       0.75      0.50      0.60         6

    accuracy                           0.81        21
   macro avg       0.79      0.72      0.74        21
weighted avg       0.80      0.81      0.80        21



In [ ]:
from sklearn.linear_model import LogisticRegression
# all parameters not specified are set to their defaults
logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)
y_pred = logisticRegr.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14  1]
 [ 4  2]]
              precision    recall  f1-score   support

        Safe       0.78      0.93      0.85        15
      Unsafe       0.67      0.33      0.44         6

    accuracy                           0.76        21
   macro avg       0.72      0.63      0.65        21
weighted avg       0.75      0.76      0.73        21



In [ ]:
from sklearn.ensemble import RandomForestClassifier
classification = RandomForestClassifier(n_estimators=50, random_state=0)
classification.fit(x_train, y_train)
y_pred = classification.predict(x_test)


# Evaluating the Algorithm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[13  2]
 [ 4  2]]
              precision    recall  f1-score   support

        Safe       0.76      0.87      0.81        15
      Unsafe       0.50      0.33      0.40         6

    accuracy                           0.71        21
   macro avg       0.63      0.60      0.61        21
weighted avg       0.69      0.71      0.69        21

0.7142857142857143


In [ ]:
from sklearn.svm import SVC
import numpy as np

# Assuming you have defined enc, enc1, enc2, enc3, enc4, and enc5 for encoding
# Your feature encoders should be consistent with the training data

# Define the input features as a list
a = ['Ramapuram', 'Ambal Nagar', 'Evening', 'Medium', 'No', 'No']

# Use your feature encoders to transform the input data
a[0] = enc.transform([a[0]])  # Assuming enc is a LabelEncoder
a[1] = enc1.transform([a[1]])  # Assuming enc1 is a LabelEncoder
a[2] = enc2.transform([a[2]])  # Assuming enc2 is a LabelEncoder
a[3] = enc3.transform([a[3]])  # Assuming enc3 is a LabelEncoder
a[4] = enc4.transform([a[4]])  # Assuming enc4 is a LabelEncoder
a[5] = enc5.transform([a[5]])  # Assuming enc5 is a LabelEncoder

# Convert the list of encoded values to a NumPy array
a = np.array(a).reshape(1, -1)  # Reshape to match the input format

# Create a SVM Classifier
svclassifier = SVC(kernel='linear')

# Fit the classifier with your training data
# X_train and y_train should be your training data
# Make sure to preprocess and prepare your training data appropriately
svclassifier.fit(x_train, y_train)

# Now you can make predictions
y_pred = svclassifier.predict(a)
print(y_pred)


['Safe']


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
